repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.6.3
    hooks:
      - id: conventional-commits
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.2
    hooks:
      - id: gitleaks
